# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StructureTreeApp' do
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'
  pod 'RxDataSources', '3.1.0'

end
